netsh http add urlacl url=http://+:8020/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:8021/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40000/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40010/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40020/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40025/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40060/ sddl=D:(A;;GA;;;WD)
netsh http add urlacl url=http://+:40200/ sddl=D:(A;;GA;;;WD)